### ISSUE TITLE
Empty Playlist

### ISSUE THREAD

**Issue by naveenland4** [techiesneh/TataSky-AutoCron#1]
Hi Bro,

I followed your procedure and a playlist has been created. But i get "Initial Test" in the m3u file.

**Comment by techiesneh** [comment]
Just follow instructions step by step
Go to ur github repo  u have new private repo
go to action tab and run workflow for girst time

if u any problems
contact me on telegram @techiesneh

**Comment by naveenland4** [comment]
> Just follow instructions step by step Go to ur github repo u have new private repo name MyTatsSky-Daily go to action tab and run workflow for first time
> 
> if u any problems contact me on telegram @techiesneh

Thanks Bro it works... You are the great....
